# Generated by Django 4.2.16 on 2024-12-18 13:40

from django.db import migrations, models
import lotion.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uid', models.CharField(default=lotion.core.models.generate_sid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('parent_uid', models.CharField(max_length=255)),
                ('child_uid', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
