# Generated by Django 4.2.16 on 2025-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_parent_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='parent_uid',
            field=models.CharField(blank=True, default='ROOT', max_length=255, null=True),
        ),
    ]
